services:
  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Bangkok
      - PYTHONWARNINGS=ignore::SyntaxWarning
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./fuction:/opt/airflow/fuction
      - ./script:/opt/airflow/script
      - ./assets/.env:/opt/airflow/assets/.env
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow standalone"